apiVersion: apps/v1
kind: Deployment
metadata:
  name: stuck-jetty-jersey
  namespace: onme
  labels:
    app: stuck-jersey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stuck-jersey
  template:
    metadata:
      labels:
        app: stuck-jersey
        tier: backend
    spec:
      containers:
        - image: registry.tsst.xyz:5000/onme/stuck-jetty-jersey:0.1.0
          imagePullPolicy: Always
          name: stuck-jersey
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
            - name: secret-volume
              mountPath: "/secret"
      volumes:
        - name: config-volume
          configMap:
            name: stuck
        - name: secret-volume
          secret:
            secretName: stuck
---
apiVersion: v1
kind: Service
metadata:
  name: stuck-jersey
  namespace: onme
spec:
  type: LoadBalancer
  selector:
    app: stuck-jersey
  ports:
    - name: stuck-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
