apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: onme
  name: stuck-jetty-jersey
  labels:
    app: stuck-jersey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuck-jersey
  template:
    metadata:
      labels:
        app: stuck-jersey
    spec:
      containers:
        - image: registry.tsst.xyz:5000/onme/stuck-jetty-jersey:0.1.0
          imagePullPolicy: Always
          name: stuck-jersey
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: stuck-jersey
  namespace: onme
spec:
  type: LoadBalancer
  selector:
    app: stuck-jersey
  ports:
    - name: stuck-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
