apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: onme
  name: stuck-gin
  labels:
    app: stuck-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stuck-gin
  template:
    metadata:
      labels:
        app: stuck-gin
        tier: backend
    spec:
      containers:
        - env:
            - name: GIN_MODE
              value: release
          image: registry.tsst.xyz:5000/onme/stuck-gin:0.1.0
          imagePullPolicy: Always
          name: stuck-gin
          ports:
            - containerPort: 8000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: stuck-gin
  namespace: onme
spec:
  type: LoadBalancer
  selector:
    app: stuck-gin
  ports:
    - name: stuck-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
