name: Python Package and Dockerize

on:
    release:
      types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gin
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
