name: Python Package and Dockerize

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches: ["main"]
  release:
    types: [created]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Prepare Dockerfile
        run: cp ./k8s/Dockerfile ./

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag onme/stuck-nextjs:$(date +%s)
